//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_Practical_Front_End.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Group_Practical_Back_End")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cart_ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Wish_ListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cart_Items {
            get {
                return this.Cart_ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.Cart_ItemsField, value) != true)) {
                    this.Cart_ItemsField = value;
                    this.RaisePropertyChanged("Cart_Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Type {
            get {
                return this.User_TypeField;
            }
            set {
                if ((this.User_TypeField.Equals(value) != true)) {
                    this.User_TypeField = value;
                    this.RaisePropertyChanged("User_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wish_List {
            get {
                return this.Wish_ListField;
            }
            set {
                if ((object.ReferenceEquals(this.Wish_ListField, value) != true)) {
                    this.Wish_ListField = value;
                    this.RaisePropertyChanged("Wish_List");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Group_Practical_Back_End")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dimensions_XYZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Discount_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Product_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Seller_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Weight_KGField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimensions_XYZ {
            get {
                return this.Dimensions_XYZField;
            }
            set {
                if ((object.ReferenceEquals(this.Dimensions_XYZField, value) != true)) {
                    this.Dimensions_XYZField = value;
                    this.RaisePropertyChanged("Dimensions_XYZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Discount_Price {
            get {
                return this.Discount_PriceField;
            }
            set {
                if ((this.Discount_PriceField.Equals(value) != true)) {
                    this.Discount_PriceField = value;
                    this.RaisePropertyChanged("Discount_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Name {
            get {
                return this.Product_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_NameField, value) != true)) {
                    this.Product_NameField = value;
                    this.RaisePropertyChanged("Product_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Product_Price {
            get {
                return this.Product_PriceField;
            }
            set {
                if ((this.Product_PriceField.Equals(value) != true)) {
                    this.Product_PriceField = value;
                    this.RaisePropertyChanged("Product_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seller_ID {
            get {
                return this.Seller_IDField;
            }
            set {
                if ((this.Seller_IDField.Equals(value) != true)) {
                    this.Seller_IDField = value;
                    this.RaisePropertyChanged("Seller_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight_KG {
            get {
                return this.Weight_KGField;
            }
            set {
                if ((this.Weight_KGField.Equals(value) != true)) {
                    this.Weight_KGField = value;
                    this.RaisePropertyChanged("Weight_KG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seller", Namespace="http://schemas.datacontract.org/2004/07/Group_Practical_Back_End")]
    [System.SerializableAttribute()]
    public partial class Seller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Average_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Identity_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Average_Rating {
            get {
                return this.Average_RatingField;
            }
            set {
                if ((this.Average_RatingField.Equals(value) != true)) {
                    this.Average_RatingField = value;
                    this.RaisePropertyChanged("Average_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identity_Number {
            get {
                return this.Identity_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Identity_NumberField, value) != true)) {
                    this.Identity_NumberField = value;
                    this.RaisePropertyChanged("Identity_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_Name {
            get {
                return this.S_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.S_NameField, value) != true)) {
                    this.S_NameField = value;
                    this.RaisePropertyChanged("S_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_Surname {
            get {
                return this.S_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.S_SurnameField, value) != true)) {
                    this.S_SurnameField = value;
                    this.RaisePropertyChanged("S_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUser", ReplyAction="http://tempuri.org/IService1/addUserResponse")]
        bool addUser(string username, string password, string surname, string name, string email, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addUser", ReplyAction="http://tempuri.org/IService1/addUserResponse")]
        System.Threading.Tasks.Task<bool> addUserAsync(string username, string password, string surname, string name, string email, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserById", ReplyAction="http://tempuri.org/IService1/getUserByIdResponse")]
        Group_Practical_Front_End.ServiceReference1.User getUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserById", ReplyAction="http://tempuri.org/IService1/getUserByIdResponse")]
        System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.User> getUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchUser", ReplyAction="http://tempuri.org/IService1/searchUserResponse")]
        bool searchUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchUser", ReplyAction="http://tempuri.org/IService1/searchUserResponse")]
        System.Threading.Tasks.Task<bool> searchUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserID", ReplyAction="http://tempuri.org/IService1/getUserIDResponse")]
        int getUserID(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUserID", ReplyAction="http://tempuri.org/IService1/getUserIDResponse")]
        System.Threading.Tasks.Task<int> getUserIDAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductByID", ReplyAction="http://tempuri.org/IService1/getProductByIDResponse")]
        Group_Practical_Front_End.ServiceReference1.Product getProductByID(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductByID", ReplyAction="http://tempuri.org/IService1/getProductByIDResponse")]
        System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.Product> getProductByIDAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSellerByID", ReplyAction="http://tempuri.org/IService1/getSellerByIDResponse")]
        Group_Practical_Front_End.ServiceReference1.Seller getSellerByID(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSellerByID", ReplyAction="http://tempuri.org/IService1/getSellerByIDResponse")]
        System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.Seller> getSellerByIDAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        Group_Practical_Front_End.ServiceReference1.Product[] getProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.Product[]> getProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProduct", ReplyAction="http://tempuri.org/IService1/addProductResponse")]
        bool addProduct(Group_Practical_Front_End.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProduct", ReplyAction="http://tempuri.org/IService1/addProductResponse")]
        System.Threading.Tasks.Task<bool> addProductAsync(Group_Practical_Front_End.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        bool editProduct(Group_Practical_Front_End.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        System.Threading.Tasks.Task<bool> editProductAsync(Group_Practical_Front_End.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addSeller", ReplyAction="http://tempuri.org/IService1/addSellerResponse")]
        bool addSeller(Group_Practical_Front_End.ServiceReference1.Seller seller);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addSeller", ReplyAction="http://tempuri.org/IService1/addSellerResponse")]
        System.Threading.Tasks.Task<bool> addSellerAsync(Group_Practical_Front_End.ServiceReference1.Seller seller);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchSeller", ReplyAction="http://tempuri.org/IService1/searchSellerResponse")]
        bool searchSeller(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchSeller", ReplyAction="http://tempuri.org/IService1/searchSellerResponse")]
        System.Threading.Tasks.Task<bool> searchSellerAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToCart", ReplyAction="http://tempuri.org/IService1/addToCartResponse")]
        bool addToCart(int UserId, int productId, int add);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToCart", ReplyAction="http://tempuri.org/IService1/addToCartResponse")]
        System.Threading.Tasks.Task<bool> addToCartAsync(int UserId, int productId, int add);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromCart", ReplyAction="http://tempuri.org/IService1/removeFromCartResponse")]
        bool removeFromCart(int UserId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromCart", ReplyAction="http://tempuri.org/IService1/removeFromCartResponse")]
        System.Threading.Tasks.Task<bool> removeFromCartAsync(int UserId, int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Group_Practical_Front_End.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Group_Practical_Front_End.ServiceReference1.IService1>, Group_Practical_Front_End.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addUser(string username, string password, string surname, string name, string email, string phone) {
            return base.Channel.addUser(username, password, surname, name, email, phone);
        }
        
        public System.Threading.Tasks.Task<bool> addUserAsync(string username, string password, string surname, string name, string email, string phone) {
            return base.Channel.addUserAsync(username, password, surname, name, email, phone);
        }
        
        public Group_Practical_Front_End.ServiceReference1.User getUserById(int id) {
            return base.Channel.getUserById(id);
        }
        
        public System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.User> getUserByIdAsync(int id) {
            return base.Channel.getUserByIdAsync(id);
        }
        
        public bool searchUser(string username, string password) {
            return base.Channel.searchUser(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> searchUserAsync(string username, string password) {
            return base.Channel.searchUserAsync(username, password);
        }
        
        public int getUserID(string username, string password) {
            return base.Channel.getUserID(username, password);
        }
        
        public System.Threading.Tasks.Task<int> getUserIDAsync(string username, string password) {
            return base.Channel.getUserIDAsync(username, password);
        }
        
        public Group_Practical_Front_End.ServiceReference1.Product getProductByID(int Id) {
            return base.Channel.getProductByID(Id);
        }
        
        public System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.Product> getProductByIDAsync(int Id) {
            return base.Channel.getProductByIDAsync(Id);
        }
        
        public Group_Practical_Front_End.ServiceReference1.Seller getSellerByID(int Id) {
            return base.Channel.getSellerByID(Id);
        }
        
        public System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.Seller> getSellerByIDAsync(int Id) {
            return base.Channel.getSellerByIDAsync(Id);
        }
        
        public Group_Practical_Front_End.ServiceReference1.Product[] getProducts() {
            return base.Channel.getProducts();
        }
        
        public System.Threading.Tasks.Task<Group_Practical_Front_End.ServiceReference1.Product[]> getProductsAsync() {
            return base.Channel.getProductsAsync();
        }
        
        public bool addProduct(Group_Practical_Front_End.ServiceReference1.Product product) {
            return base.Channel.addProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> addProductAsync(Group_Practical_Front_End.ServiceReference1.Product product) {
            return base.Channel.addProductAsync(product);
        }
        
        public bool editProduct(Group_Practical_Front_End.ServiceReference1.Product product) {
            return base.Channel.editProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> editProductAsync(Group_Practical_Front_End.ServiceReference1.Product product) {
            return base.Channel.editProductAsync(product);
        }
        
        public bool addSeller(Group_Practical_Front_End.ServiceReference1.Seller seller) {
            return base.Channel.addSeller(seller);
        }
        
        public System.Threading.Tasks.Task<bool> addSellerAsync(Group_Practical_Front_End.ServiceReference1.Seller seller) {
            return base.Channel.addSellerAsync(seller);
        }
        
        public bool searchSeller(string username, string password) {
            return base.Channel.searchSeller(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> searchSellerAsync(string username, string password) {
            return base.Channel.searchSellerAsync(username, password);
        }
        
        public bool addToCart(int UserId, int productId, int add) {
            return base.Channel.addToCart(UserId, productId, add);
        }
        
        public System.Threading.Tasks.Task<bool> addToCartAsync(int UserId, int productId, int add) {
            return base.Channel.addToCartAsync(UserId, productId, add);
        }
        
        public bool removeFromCart(int UserId, int productId) {
            return base.Channel.removeFromCart(UserId, productId);
        }
        
        public System.Threading.Tasks.Task<bool> removeFromCartAsync(int UserId, int productId) {
            return base.Channel.removeFromCartAsync(UserId, productId);
        }
    }
}
